---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # there's a regression with mysql cookbook in 12.4.0
  require_chef_omnibus: 12.3.0

platforms:
  - name: centos-7.1
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
    - recipe[teampass::default]
    attributes:
